### ISSUE TITLE
QT5.9编译失败

### ISSUE THREAD

**Issue by updown01** [Cillebokin/ProQtGraphics#1]

**Comment by Bruce2019tss** [comment]
您好：
按照您的提示，还是无法编译通过，问题描述：”👎 error: No rule to make target 'D:/desk/demo/ProQtGraphics/ProQtQGraphics/ProQtQGraphics/libs/libX_Netd.a', needed by 'debug/ProQtQGraphics.exe'. Stop.“。 
作者方便私聊吗（QQ:2668057612 ），本人愿意有偿答谢（如何可以的话，希望您能发现工作文件给我，邮箱：2668057612@qq.com）。
